services:
  neo-4j:
    build: ${NEO4J_TARGET}
    container_name: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    env_file:
    - path: ./.env
      required: true
  mcp_backend:
    volumes:
      - ${NEO4J_TARGET}/graph:/app/resources
    build:
      context: ./mcp       
      dockerfile: ./backend/Dockerfile 
    container_name: mcp_fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      neo-4j:
        condition: service_healthy
    env_file:
    - path: ./.env
      required: true
  mcp_frontend:
    build:
      context: ./mcp/frontend       
      args:
        - FONT_SIZE=${FONT_SIZE}
    container_name: mcp_flask_frontend
    ports:
      - "5000:5000"
    depends_on:
      - mcp_backend
    env_file:
    - path: ./.env
      required: true
  overview_frontend:
    build:
      context: ./overview/frontend
      args:
        - FONT_SIZE=${FONT_SIZE}
    container_name: overview_flask_frontend
    ports:
      - "5003:5003"
    volumes:
      - ${NEO4J_TARGET}/graph:/app/resources
    depends_on:
      - mcp_backend
    env_file:
    - path: ./.env
      required: true
  semantic_search_backend:
    volumes:
      - ${NEO4J_TARGET}/graph:/app/resources
    build:
      context: ./semantic_search/        
      dockerfile: ./backend/Dockerfile 
    container_name: semantic_search_fastapi_backend
    ports:
      - "8001:8001"
    env_file:
    - path: ./.env
      required: true
  semantic_search_frontend:
    build: 
     context: ./semantic_search/frontend
     args:
        - PORTAL_NAME=${PORTAL_NAME}
    container_name: semantic_search_flask_frontend
    ports:
      - "5001:5001"
    depends_on:
      - semantic_search_backend
      - neo-4j
    env_file:
    - path: ./.env
      required: true
  genomic_index_query_backend:
    build:
      context: ./genomic_index          # directory used as build context
      dockerfile: ./genomic_index_query_backend/Dockerfile
    container_name: genomic-index-query-backend
    ports:
      - "8002:8002"
    volumes:
      - ./genomic_index/mantis_index:/sw/mantis_index
      - ${NEO4J_TARGET}/graph:/app/resources
    env_file:
    - path: ./.env
      required: true
  genomic_index_query_frontend:
    build: ./genomic_index/genomic_index_query_frontend
    container_name: genomic-index-query-frontend
    ports:
      - "5002:5002"
    depends_on:
      - genomic_index_query_backend
    env_file:
    - path: ./.env
      required: true