FROM --platform=linux/amd64 ubuntu:22.04

WORKDIR /sw

## install CLI packages
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3.10-dev \
    python3-pip \
    build-essential \
    cmake \
    git \
    zlib1g-dev \
    libbz2-dev \
    libssl-dev \
    libboost-all-dev \
    vim \
    && rm -rf /var/lib/apt/lists/*

## install squeakr
RUN git clone https://github.com/splatlab/squeakr.git
RUN cd squeakr && make squeakr
RUN mv squeakr/squeakr /bin/

## install SDSL
RUN git clone https://github.com/simongog/sdsl-lite.git
RUN cd sdsl-lite && ./install.sh /usr/local

## install mantis
RUN git clone https://github.com/splatlab/mantis.git
RUN mkdir /sw/mantis/build && \
    cd /sw/mantis/build && \
    cmake .. -DCMAKE_CXX_FLAGS="-include cstdint -include cstddef -include string" && \
    make install

## install python dependencies 
COPY pyproject.toml /sw/pyproject.toml
RUN pip install --upgrade pip && \
    pip install "pysb @ git+https://github.com/pysb/pysb.git"

## copy source and install 
COPY dglink /sw/dglink
RUN pip install -e ./

## copy scripts
COPY dglink/applications/genomic_index/scripts /sw/scripts
